<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\Forme.MonoGame.GPU.Demo.Shared\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Forme.MonoGame.GPU.Demo.Shared\Forme.MonoGame.GPU.Demo.Shared.csproj" />
    <MonoGameContentReference Include="..\Forme.MonoGame.GPU.Demo.Shared\Content\Content.mgcb">
      <Link>Content\Content.mgcb</Link>
      <Platform>Windows</Platform>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="$(MonoGameVersion)" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="$(MonoGameVersion)" />
  </ItemGroup>
</Project>
