<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>CnCNet.Forme.NET48</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.12" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Forme.MonoGame</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
