<?xml version="1.0" encoding="utf-8"?>
<Project>

    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

    <PropertyGroup>
        <ArtifactsPath>$(SolutionDirectory).artifacts/src</ArtifactsPath>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsPackable>true</IsPackable>
        <NoWarn>NU1701</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!-- Prevent Polyfill extension types from leaking between assemblies in the library graph -->
        <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
    </PropertyGroup>

</Project>
