<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net48</TargetFrameworks>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.DesktopGL"
                          Version="$(MonoGameVersion)"
                          PrivateAssets="All" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Forme.MonoGame\Forme.MonoGame.csproj" />
    </ItemGroup>
</Project>
